import { StyleSheet } from "react-native";

export const theme = {
  colors: {
    background: "#050706",
    surface: "#0E120E",
    surfaceMuted: "#171C17",
    text: "#F4FFF1",
    textMuted: "#A7B1A3",
    border: "#252D25",
    primary: "#A8FF1A",
    primaryDark: "#D7FF5F",
    ink: "#050706",
    successSurface: "#16240D",
    successBorder: "#B6FF00",
    warningSurface: "#241A08",
    warningBorder: "#F59E0B",
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 44,
  },
};

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: theme.colors.background,
    width: "100%",
  },
  header: {
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.sm,
    paddingTop: theme.spacing.lg,
    width: "100%",
  },
  brandRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  appName: {
    color: theme.colors.primary,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0,
  },
  headerMeta: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  headerPill: {
    backgroundColor: "transparent",
    borderColor: theme.colors.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  headerPillText: {
    color: theme.colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
  },
  screenTitle: {
    alignSelf: "stretch",
    color: theme.colors.text,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 0,
    marginTop: theme.spacing.sm,
    width: "100%",
  },
  tabScroller: {
    maxHeight: 58,
  },
  tabRow: {
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
  },
  tabButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    minWidth: 78,
    paddingHorizontal: theme.spacing.md,
  },
  tabButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  tabButtonText: {
    color: theme.colors.textMuted,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0,
  },
  tabButtonTextActive: {
    color: theme.colors.ink,
  },
  content: {
    flex: 1,
    width: "100%",
  },
  contentInner: {
    gap: theme.spacing.lg,
    padding: theme.spacing.lg,
    paddingBottom: theme.spacing.xxl,
  },
  authPage: {
    gap: theme.spacing.lg,
  },
  logoPage: {
    alignItems: "center",
    gap: theme.spacing.xl,
    justifyContent: "center",
    minHeight: 720,
    paddingHorizontal: theme.spacing.md,
    paddingTop: theme.spacing.xl,
  },
  logoImage: {
    borderRadius: 28,
    height: 180,
    width: 180,
  },
  logoHero: {
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  logoName: {
    color: theme.colors.primary,
    fontSize: 42,
    fontWeight: "900",
    letterSpacing: 1,
  },
  logoTagline: {
    color: theme.colors.textMuted,
    fontSize: 16,
    lineHeight: 23,
    maxWidth: 320,
    textAlign: "center",
  },
  logoActionPanel: {
    alignSelf: "stretch",
    gap: theme.spacing.md,
  },
  authLinkButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    minHeight: 48,
    justifyContent: "center",
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  authLinkText: {
    color: theme.colors.primary,
    fontSize: 15,
    fontWeight: "800",
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
  },
  heroPanel: {
    alignItems: "center",
    backgroundColor: "#080B08",
    borderColor: "#34401F",
    borderRadius: 18,
    borderWidth: 1,
    gap: theme.spacing.sm,
    padding: theme.spacing.lg,
  },
  heroTitle: {
    color: theme.colors.text,
    fontSize: 30,
    fontWeight: "900",
    letterSpacing: 0,
    lineHeight: 34,
    textAlign: "center",
  },
  authLogoImage: {
    borderRadius: 18,
    height: 112,
    width: 112,
  },
  heroBody: {
    color: theme.colors.textMuted,
    fontSize: 16,
    lineHeight: 23,
  },
  warningCard: {
    backgroundColor: theme.colors.warningSurface,
    borderColor: theme.colors.warningBorder,
  },
  eyebrow: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  heading: {
    color: theme.colors.text,
    fontSize: 22,
    fontWeight: "800",
    letterSpacing: 0,
  },
  body: {
    color: theme.colors.text,
    fontSize: 16,
    lineHeight: 23,
  },
  metricGrid: {
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  metricTile: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    minHeight: 78,
    justifyContent: "center",
    padding: theme.spacing.sm,
  },
  metricValue: {
    color: theme.colors.primary,
    fontSize: 20,
    fontWeight: "900",
  },
  metricLabel: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  clockPanel: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
  },
  clockHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  clockBadge: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  clockBadgeText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  clockSummary: {
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  clockSummaryItem: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    padding: theme.spacing.md,
  },
  clockTime: {
    color: theme.colors.text,
    fontSize: 20,
    fontWeight: "900",
  },
  clockButtonRow: {
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  clockPrimaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 58,
  },
  clockPrimaryButtonText: {
    color: theme.colors.ink,
    fontSize: 17,
    fontWeight: "900",
  },
  clockSecondaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 58,
  },
  clockSecondaryButtonText: {
    color: theme.colors.primary,
    fontSize: 17,
    fontWeight: "900",
  },
  disabledButton: {
    opacity: 0.45,
  },
  mapPanel: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: theme.spacing.md,
    padding: theme.spacing.md,
  },
  mapPlaceholder: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 180,
    padding: theme.spacing.md,
  },
  mapPlaceholderText: {
    color: theme.colors.textMuted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
    textAlign: "center",
  },
  locationValue: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: "900",
  },
  inputLabel: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  textInput: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    color: theme.colors.text,
    fontSize: 16,
    minHeight: 54,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  passwordInputRow: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  passwordTextInput: {
    flex: 1,
  },
  passwordToggleButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 54,
    minWidth: 62,
  },
  passwordToggleSymbol: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  checkboxRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: theme.spacing.sm,
    minHeight: 42,
  },
  checkboxBox: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  checkboxBoxChecked: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  checkboxMark: {
    color: theme.colors.ink,
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 22,
  },
  checkboxLabel: {
    color: theme.colors.text,
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
  },
  textArea: {
    minHeight: 104,
    textAlignVertical: "top",
  },
  verificationCodeInput: {
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: 8,
    textAlign: "center",
  },
  textAreaSmall: {
    minHeight: 78,
    textAlignVertical: "top",
  },
  inlineFormPanel: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  locationInputRow: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  locationTextInput: {
    flex: 1,
  },
  locationIconButton: {
    alignItems: "center",
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 54,
    minWidth: 82,
    paddingHorizontal: theme.spacing.sm,
  },
  locationIconText: {
    color: theme.colors.ink,
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 24,
  },
  locationIconLabel: {
    color: theme.colors.ink,
    fontSize: 11,
    fontWeight: "900",
  },
  previewPanel: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: theme.spacing.sm,
    padding: theme.spacing.sm,
  },
  evidencePreviewImage: {
    borderRadius: 12,
    height: 240,
    width: "100%",
  },
  reportPreviewImage: {
    borderRadius: 12,
    height: 96,
    width: 96,
  },
  muted: {
    color: theme.colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  list: {
    gap: theme.spacing.sm,
  },
  row: {
    alignItems: "center",
    borderColor: theme.colors.border,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: theme.spacing.sm,
  },
  recentTimeContent: {
    flex: 1,
    gap: theme.spacing.sm,
  },
  recentTimeActions: {
    alignItems: "flex-end",
    gap: theme.spacing.sm,
  },
  deleteConfirmRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.xs,
    justifyContent: "flex-end",
  },
  rowLabel: {
    color: theme.colors.textMuted,
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
  },
  rowValue: {
    color: theme.colors.text,
    flex: 1,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "right",
  },
  actionRow: {
    gap: theme.spacing.sm,
  },
  actionButton: {
    alignItems: "center",
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 54,
    justifyContent: "center",
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  actionButtonSecondary: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 54,
    justifyContent: "center",
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  compactSecondaryButton: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
  },
  compactSecondaryButtonText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: "900",
  },
  compactDangerButton: {
    alignItems: "center",
    backgroundColor: theme.colors.warningSurface,
    borderColor: theme.colors.warningBorder,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
  },
  compactDangerButtonText: {
    color: "#FFD166",
    fontSize: 13,
    fontWeight: "900",
  },
  actionButtonText: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  actionButtonSubtext: {
    color: "#405020",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  actionButtonSecondaryText: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: "800",
  },
  actionButtonSecondarySubtext: {
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  quickGrid: {
    gap: theme.spacing.sm,
  },
  quickActionPrimary: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    minHeight: 68,
    justifyContent: "center",
    padding: theme.spacing.md,
  },
  quickAction: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    minHeight: 62,
    justifyContent: "center",
    padding: theme.spacing.md,
  },
  quickActionTitle: {
    color: theme.colors.primary,
    fontSize: 16,
    fontWeight: "900",
  },
  quickActionText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: "700",
  },
  stepList: {
    gap: theme.spacing.sm,
  },
  stepRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: theme.spacing.sm,
  },
  stepNumber: {
    backgroundColor: theme.colors.primary,
    borderRadius: 8,
    color: theme.colors.ink,
    fontSize: 14,
    fontWeight: "900",
    height: 30,
    lineHeight: 30,
    overflow: "hidden",
    textAlign: "center",
    width: 30,
  },
  statusCard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: theme.spacing.sm,
    padding: theme.spacing.lg,
  },
  statusTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  statusMessage: {
    color: theme.colors.textMuted,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
  },
  codePreview: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 999,
    borderWidth: 1,
    color: theme.colors.text,
    fontFamily: "monospace",
    fontSize: 12,
    lineHeight: 17,
    padding: theme.spacing.sm,
  },
  statusPill: {
    alignSelf: "flex-start",
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: 8,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  statusPillText: {
    color: theme.colors.primary,
    fontSize: 13,
    fontWeight: "800",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.sm,
  },
  chip: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  chipActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  chipText: {
    color: theme.colors.textMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  chipActiveText: {
    color: theme.colors.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  dropdownContainer: {
    gap: theme.spacing.xs,
  },
  dropdownBox: {
    alignItems: "center",
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
  },
  dropdownValue: {
    color: theme.colors.text,
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
  },
  dropdownChevron: {
    color: theme.colors.primary,
    fontSize: 13,
    fontWeight: "900",
    marginLeft: theme.spacing.sm,
  },
  dropdownMenu: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
  },
  dropdownOption: {
    borderBottomColor: theme.colors.border,
    borderBottomWidth: 1,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
  },
  dropdownOptionActive: {
    backgroundColor: theme.colors.primary,
    borderBottomColor: theme.colors.primary,
    borderBottomWidth: 1,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.md,
  },
  dropdownOptionText: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: "700",
  },
  dropdownOptionActiveText: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: "900",
  },
});
